language: node_js

node_js:
  - '4.2'

sudo: false

cache:
  directories:
    - node_modules
    - vendor/bundle

git:
  submodules: false

before_install:
  - ruby --version
  - gem --version
  - gem install bundler --quiet --no-ri --no-rdoc
  - bundle --version
  - bundle install --without documentation --path vendor/bundle
  - npm install -g grunt-cli
  - grunt --version

script:
  - npm start